### ISSUE TITLE
Keeping 'thead' and paginating only 'tbody'

### ISSUE THREAD

**Issue by pedronoliveira** [conductrics/bootstrap-table-nav#4]
Would be kind of useful to do that, been trying to find out on the JS how to do that, but if the childSelector property is changed from 'tr' to another markdown, the script breaks, I'll try to dig this deeper.
If anyone has and idea on how to do this, please share.

**Comment by pedronoliveira** [comment]
Nevermind, I guess that if you add #tbody to the bootstrap-table-nav script it works the same!

**Comment by erswelljustin** [comment]
Can you show an example of this?
